<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WashGo.HttpApi.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\WashGo.HttpApi\WashGo.HttpApi.csproj" />
    <ProjectReference Include="..\src\WashGo.Application\WashGo.Application.csproj" />
    <ProjectReference Include="..\src\WashGo.EntityFrameworkCore\WashGo.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Autofac" Version="8.2.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="8.2.0" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="8.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
  </ItemGroup>

</Project>
