<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WashGo.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WashGo.Application.Contracts\WashGo.Application.Contracts.csproj" />
    <ProjectReference Include="..\WashGo.Domain\WashGo.Domain.csproj" />
    <ProjectReference Include="..\Core\WashGo.Core\WashGo.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="8.2.0" />
    <PackageReference Include="Volo.Abp.AutoMapper" Version="8.2.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
  </ItemGroup>

</Project>
