<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WashGo.Core.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WashGo.Core.Domain.Shared\WashGo.Core.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="8.2.0" />
    <PackageReference Include="Npgsql" Version="8.0.4" />
  </ItemGroup>

</Project>
